dist: xenial
language: minimal

services:
  - docker

script:
  - docker-compose -f docker-compose.test.yml up --build  --abort-on-container-exit --exit-code-from sut

notifications:
  email:
    on_success: change
    on_failure: always
