# Generated by Django 3.2.12 on 2022-03-03 10:51

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import phorum.models
import phorum.models.fields
import phorum.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('phorum', '0004_room_god_can_delete_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='god_can_delete_posts',
            field=models.BooleanField(default=True, verbose_name='god může mazat příspěvky'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_override',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Green ribbon'), (1, 'Yellow ribbon'), (2, 'Orange ribbon'), (3, 'Red ribbon'), (4, 'Maroon ribbon'), (5, '1 dot'), (6, '2 dots'), (7, '3 dots'), (8, 'God'), (15, 'Admin'), (16, 'Editor'), (99, 'Dev')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_thread_roots',
            field=models.SmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='počet threadů na stránku'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='usercustomization',
            name='custom_css',
            field=phorum.models.fields.RawContentFileField(blank=True, null=True, storage=phorum.models.OverwritingFileSystemStorage(base_url='/protected'), upload_to=phorum.models.utils.css_upload_path, verbose_name='Vlastní CSS'),
        ),
        migrations.AlterField(
            model_name='usercustomization',
            name='custom_js',
            field=phorum.models.fields.RawContentFileField(blank=True, null=True, storage=phorum.models.OverwritingFileSystemStorage(base_url='/protected'), upload_to=phorum.models.utils.js_upload_path, verbose_name='Vlastní JS'),
        ),
    ]
