# Generated by Django 3.2.12 on 2022-03-03 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phorum', '0005_auto_20220303_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
